// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOzkjeKiwTFnwMSUOc408koiaSYttcrHQ',
    appId: '1:459888383369:web:3fb80241f729c0473b3d58',
    messagingSenderId: '459888383369',
    projectId: 'caretocare-12',
    authDomain: 'caretocare-12.firebaseapp.com',
    storageBucket: 'caretocare-12.appspot.com',
    measurementId: 'G-2WFYVTQYVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC-4xzv1UOGngiR0qu5ECciMza9oGmuEE',
    appId: '1:459888383369:android:18acaf4e44c6cb153b3d58',
    messagingSenderId: '459888383369',
    projectId: 'caretocare-12',
    storageBucket: 'caretocare-12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd5apNEp2o9-4hb81U49f_6e0ImQugA2Q',
    appId: '1:459888383369:ios:f2e5b689f91847de3b3d58',
    messagingSenderId: '459888383369',
    projectId: 'caretocare-12',
    storageBucket: 'caretocare-12.appspot.com',
    iosBundleId: 'com.example.careToCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd5apNEp2o9-4hb81U49f_6e0ImQugA2Q',
    appId: '1:459888383369:ios:f2e5b689f91847de3b3d58',
    messagingSenderId: '459888383369',
    projectId: 'caretocare-12',
    storageBucket: 'caretocare-12.appspot.com',
    iosBundleId: 'com.example.careToCare',
  );
}
